public class BattleProperty { public int Value { get; set; } = 0; }
public class HP_BattleProperty : BattleProperty { }
public class DEF_BattleProperty : BattleProperty { }
public class ATK_BattleProperty : BattleProperty { }
public class ATK_SPD_BattleProperty : BattleProperty { }
public class Stun_BattleProperty : BattleProperty { }
public class Evasion_BattleProperty : BattleProperty { }
public class Regeneration_BattleProperty : BattleProperty { }
public class Ignore_Stun_BattleProperty : BattleProperty { }
public class Ignore_Evasion_BattleProperty : BattleProperty { }
public class Ignore_Combo_BattleProperty : BattleProperty { }
public class Ignore_Counter_BattleProperty : BattleProperty { }
public class Crit_Dmg_BattleProperty : BattleProperty { }
public class Crit_Res_BattleProperty : BattleProperty { }
public class Basic_Atk_Dmg_BattleProperty : BattleProperty { }
public class Basic_Atk_Res_BattleProperty : BattleProperty { }
public class Combo_Dmg_BattleProperty : BattleProperty { }
public class Combo_Res_BattleProperty : BattleProperty { }
public class Counter_Dmg_BattleProperty : BattleProperty { }
public class Counter_Res_BattleProperty : BattleProperty { }
public class Launch_BattleProperty : BattleProperty { }
public class Ignore_Launch_BattleProperty : BattleProperty { }
public class Skill_Crit_Dmg_BattleProperty : BattleProperty { }
public class Skill_Dmg_BattleProperty : BattleProperty { }
public class Skill_Res_BattleProperty : BattleProperty { }
public class Pal_Dmg_BattleProperty : BattleProperty { }
public class Pal_Res_BattleProperty : BattleProperty { }
public class Healing_Rate_BattleProperty : BattleProperty { }
public class Healing_Amount_BattleProperty : BattleProperty { }
public class Skill_CD_Reduction_BattleProperty : BattleProperty { }
public class Wound_BattleProperty : BattleProperty { }
public class Counter_Regen_BattleProperty : BattleProperty { }
public class Combo_Regen_BattleProperty : BattleProperty { }
public class Pal_Regen_BattleProperty : BattleProperty { }
public class Skill_Regen_BattleProperty : BattleProperty { }
public class Pal_Crit_Dmg_BattleProperty : BattleProperty { }
public class Pal_Atk_Spd_BattleProperty : BattleProperty { }
public class Pal_Ignore_Evasion_BattleProperty : BattleProperty { }
public class Healing_Inc_Rate_BattleProperty : BattleProperty { }
public class Special_Effect_BattleProperty : BattleProperty { }
